# Generated by Django 3.2.23 on 2024-02-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialapp', '0002_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
